apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service
spec: 
  selector: 
    app: frontend-app 
  ports: 
  - name: http 
    targetPort: 8080 
    port: 80
  type: LoadBalancer 