apiVersion: apps/v1
kind: Deployment  
metadata:
  name: my-deployment
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: student-app
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: student-app
    spec:
      containers:
      - name: my-app
        image: nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP 
