apiVersion: v1
kind: Pod
metadata:
  name: my-pod 
  labels: 
   app: xyz-app 
spec:
  containers:
  - name: my-pod-container 
    image: nginx
    ports:
      - name: http
        protocol: TCP
        containerPort: 80 
        