---
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: xyz-app
spec:
  containers:
  - name: my-app
    image: nginx
    ports:
    - name: http
      containerPort: 80
      protocol: TCP 
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
  - name: my-http
    port: 80
    targetPort: 80
    protocol: TCP