apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-pod-container 
    image: nginx
    ports:
      - name: http
        protocol: TCP
        containerPort: 80