apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: my-ss 
spec: 
  replicas: 3
  serviceName: mariadb
  selector: 
    matchLabels: 
      app: mariadb 
  template: 
    metadata: 
      labels:
        app: mariadb
    spec:
      containers:
      - name: my-mariadb-container
        image: mysql 
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP 
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: my-sec 
              key: DB_PASSWORD 
        - name: MYSQL_USER_NAME 
          valueFrom: 
            secretKeyRef: 
              name: my-sec
              key: DB_USER
