apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: my-ss 
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: mariadb 
  serviceName: mariadb
  template: 
    metadata: 
      labels:
        app: mariadb
    spec:
      containers:
      - name: my-mariadb-container
        image: mysql 
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP 
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: "REDHAT"

